### ISSUE TITLE
Bug: Equipment sometimes not equipped/unequipped

### ISSUE THREAD

**Issue by zdxn** [zdxn/ValkyriesFall#3]
Issue:
Sometimes when dealing with equipment management and switching back to fights, players equipment is not actually equipped / unequipped. I've noticed a few times now that my gear after I thought had been equipped (Equipment display showed that my weapon had been equipped), I will proceed to fight a monster and realize on the new combat screen I do not have a weapon equipped. This does not happen often but it does happen. I am not actually sure if its just visual or if its actually being represented in game state during combat correctly.

Resolution: 
Equipment UI element should properly display state of currently equipped gear.

Urgency:
6

**Comment by DavePearcey** [comment]
Need replication steps as I'm unable to get this to happen.
