### ISSUE TITLE
Bug: Gold bonus does not provide additional gold.

### ISSUE THREAD

**Issue by zdxn** [zdxn/ValkyriesFall#6]
Issue;
Gold after increasing bonus gold % was not altered at end of fight. Could be a display bug, I did not do the math.

Resolution:
Provide % extra gold after kills, or modify display to show proper gold.

Urgency:
10

**Comment by DavePearcey** [comment]
Fixed gold/exp bonuses using an int in their calculations causing return of an int, not double
