### ISSUE TITLE
Feature Request: Prevent people below level 1,000 from using diamonds in marketplace

### ISSUE THREAD

**Issue by zdxn** [zdxn/ValkyriesFall#7]
Issue:
Players can create alternate accounts, accept the achievement for starting the game and purchase items from their mains using the market place to stack diamonds / bonuses on a single char. 

Resolution:
Players should not be able to abuse the achievement system on new accounts to get diamonds. Preventing item purchases until level 1,000 should be effective. 

Urgency:
10

**Comment by DavePearcey** [comment]
Have removed the diamond reward and now only gives 1000 gold.
