### ISSUE TITLE
Bug: Exp overflow is lost on level up

### ISSUE THREAD

**Issue by zdxn** [zdxn/ValkyriesFall#9]
Issue: 
When killing monsters, if a player were to level up after they were granted exp, the overflow is lost.

Resolution:
Players should retain whatever exp would be left after granting them a level.

Urgency:
1

**Comment by DavePearcey** [comment]
This was intentional. Perhaps I'll consider how to make it work where would wont get multiple levels per fight.

**Comment by zdxn** [comment]
I figured this was intentional to prevent leveling multiple times. Unsure how its coded but this could remain in place just need to make sure its clear to users the loss is expected.

Ideally carry over would be better, I havent been in a situation yet where my exp would go over so much that i would level twice. But i also have no upgrades.

**Comment by DavePearcey** [comment]
added message for now.
